### ISSUE TITLE
hello world produces nothing on stdout

### ISSUE THREAD

**Issue by dckc** [rchain-community/rchain.cloud#15]
I visited https://rchain.cloud/ and hit **Run**. A label changes to UPLOADING and then an EVALUATING section shows me a canonical version of the code from the left. Then an empty STORAGE CONTENTS section and COMPLETED heading come up. That's it.

If I expand STORAGE CONTENTS, I get an overwhelming pile of stuff.

I see #10 where handling stdout was considered done, but it doesn't look like it to me.

I can imagine this is a regression. Would you please display versions of everything that goes into the service?

**Comment by tschoffelen** [comment]
This is the way it is supposed to look:

![image](https://user-images.githubusercontent.com/666220/42230192-40bcf582-7ee0-11e8-8c47-a8177751fe88.png)

The biggest thing I'm aware of currently that stops this from working correctly is #13. Storage contents indeed contains a lot of stuff right now, since there is no mechanism in place to automatically restart nodes after X amount of requests, also discussed in #13.

Let me know if that's enough context to close this issue and continue in #13, or if you feel this is a separate problem.
