### ISSUE TITLE
Display correct line number of error

### ISSUE THREAD

**Issue by wangjia184** [rchain-community/rchain.cloud#16]
Run the following code
```
new print in {
  contract print(@list, @index) = {
    @"stdout"!(list[index])
  } |
  print!([1,4,6,2],1)
}
```
it ends with an error **Error: Unrecoverable Syntax Error**

The error is expected but it does not show the line number which caused it.
Perhaps it could display the file+linenumber from log for the errors.

**Comment by tschoffelen** [comment]
As far as I can tell, the Rnode client currently simply doesn’t report that information, since we output exactly what it outputs to the terminal usually.

Do you know of a way to get this info?

**Comment by JoshOrndorff** [comment]
The situation has changed in the meantime. The node now does print details about the error location. But for some reason the number always comes out two lines too high. If I make a mistake in line 3, rchain.cloud tells me the mistake is in line 5. This problem is unique to rchain.cloud. It works correctly locally.

**Comment by tschoffelen** [comment]
@JoshOrndorff very good catch. I experienced that problem too, but only realised what caused it when reading your comment. 

Should be fixed when my new commit is deployed in a few minutes.
