### ISSUE TITLE
show rnode version

### ISSUE THREAD

**Issue by dckc** [rchain-community/rchain.cloud#33]
Please display the version (version number, date, and short git hash) of rnode that the service is connected to.

**Comment by JoshOrndorff** [comment]
Bonus points for allowing the user to select from among a few versions.

**Comment by tschoffelen** [comment]
@JoshOrndorff We used to have that feature, but had to remove it due to the different node version having such big differences in how they behaved that supporting all of them was not doable within the scope of this project. 

That was back around v0.2-v0.3 though, so now that the node is getting more consistent across versions we should probably consider adding that feature back in at some point!

**Comment by tschoffelen** [comment]
FYI, cross referencing: the main functionality proposed by @dckc is currently being developed in PR #37 by @edisinovcic.

**Comment by dckc** [comment]
I'm glad to see progress, though I can't confirm that this is working. I'm getting **Error while evaluating: Error: Request timeout**
